export const ADD_DISH = 'ADD_DISH';

export const REMOVE_DISH = 'REMOVE_DISH';
export const INCREMENT_DISH = 'INCREMENT_DISH';
export const DECREMENT_DISH = 'DECREMENT_DISH';
export const CALCULATIOTOTALPRICE = 'CALCULATIOTOTALPRICE';
